spring:
  application:
    name: sn-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

#security:
#  user:
#    password: ${CONFIG_SERVICE_PASSWORD}
spring.jmx.default-domain: com.social.network.config
logging:
  file: /Logs/SocialNetwork/${spring.application.name}.log