logging:
  level:
    org.springframework.security: INFO
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka-server/eureka/
