logging:
  level:
    org.springframework.security: INFO
    com.social.network: DEBUG
eureka:
  instance:    
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/SNServer/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/AuthService/user/current