# Spring properties
spring:
  application:
     name: message-service  # Service registers under this name

server:
  port: 2222   # HTTP (Tomcat) port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka-server/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION


      



